name: Automatic Builds

on:
  push:
    branches:
    - master

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Install wxWidgets and PortAudio
      run: |
        sudo apt-key adv --fetch-keys https://repos.codelite.org/CodeLite.asc 
        sudo apt-add-repository 'deb https://repos.codelite.org/wx3.1.4/ubuntu/ focal universe' 
        sudo apt update 
        sudo apt install libwxgtk3.1-dev portaudio19-dev -y
    - name: Checkout
      uses: actions/checkout@v1
    - name: Compile
      run: make -j$(nproc)
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: noods-linux
        path: noods

  build-mac:
    runs-on: macos-latest

    steps:
    - name: Install wxWidgets and PortAudio
      run: brew install wxmac portaudio
    - name: Checkout
      uses: actions/checkout@v1
    - name: Compile
      run: |
        make -j$(sysctl -n hw.logicalcpu)
        ./mac-bundle.sh
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: noods-mac
        path: NooDS.app

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: msys2/setup-msys2@v2
      with:
          msystem: MINGW64
          update: true

    - name: Install build tools, wxWidgets, and PortAudio
      run: |
        pacman -S mingw-w64-x86_64-{gcc,wxWidgets,portaudio,jbigkit] make --noconfirm
    - name: Compile
      run: |
        make -j$(nproc)
        strip noods.exe
      working-directory: ${{runner.workspace}}
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: noods-windows
        path: noods.exe

  build-switch:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - uses: actions/checkout@v1
    - name: Downgrade devkitA64 to r14
      run: |
        sudo dkp-pacman -Rs devkitA64 devkitA64-gdb devkita64-rules --noconfirm
        wget "https://wii.leseratte10.de/devkitPro/devkitA64/r14 (2019-12)/devkitA64-r14-3-linux.pkg.tar.xz"
        sudo dkp-pacman -U devkitA64-r14-3-linux.pkg.tar.xz --noconfirm
    - name: Compile
      run: make -f Makefile.switch -j$(nproc)
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: noods-switch
        path: noods.nro

  build-android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Compile
      run: |
        ./gradlew assembleRelease
        mv build-android/outputs/apk/release/android-release-unsigned.apk noods.apk
    - name: Sign
      run: $ANDROID_SDK_ROOT/build-tools/29.0.3/apksigner sign --ks keystore.jks --ks-pass pass:$KEYSTORE_PASS noods.apk
      env:
        KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: noods-android
        path: noods.apk
